version: '3.1'

services:
  app:
   build: .
   ports:
    - 8000:8000
   expose:
    - 8000
   restart: always
   networks:
    - production-network
   links:
    - "db"
   depends_on:
    - "db"

  db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - .:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: usr_cambio
      POSTGRES_PASSWORD: 123456
    networks:
      - production-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - production-network

networks:
    production-network:
        driver: bridge
